spring:
  application:
    name: zeus-app2

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.oauth.model
  global-config:
    db-config:
      id-type: auto

#uaa使用端口
server:
  port: 8773